title: SDR Lab
description: Software Defined Radio Lab â€” manuals, experiments, and instructional videos

url: "https://fgx-hgf.github.io"
baseurl: "/sdr-lab-website"

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache
collections:
  pages:
    output: true
    permalink: /:path/
